### ISSUE TITLE
Setup github action to run e2e tests

### ISSUE THREAD

**Issue by moncapitaine** [progwise/george-ai#457]
# Setup GitHub Action to Run E2E Tests

## Context

**Dependency Status:** ✅ Issue #328 (Playwright End2End Login Tests locally) is **CLOSED**

We have a working Playwright setup with one login test running locally. Now we need to automate these tests in GitHub Actions CI/CD pipeline to run on every PR and push.

### ✅ Completed
- Issue #328 (Playwright local setup) is CLOSED
- Playwright 1.52.0 configured and working (`e2e-tests/playwright.config.ts`)
- Login e2e test exists (`e2e-tests/src/login.spec.ts`)
- Docker Compose has all required services (`.devcontainer/docker-compose.yml`)
- Unit tests already run in CI with PostgreSQL service (`.github/workflows/basic-checks.yml:98-126`)

### ❌ What's Needed

The original issue description lists "Setup dockers inside the github action" but the **real work** is creating a new GitHub Actions workflow that:

1. **Creates a new workflow file**: `.github/workflows/e2e-tests.yml`
2. **Configures GitHub Actions services** for databases and Typesense
3. **Builds application Docker containers** (backend, frontend)
4. **Installs Playwright browsers** in CI environment
5. **Runs existing e2e tests** with proper wait/health checks
6. **Uploads test artifacts** (screenshots, videos, HTML report) on failure

**Why this is critical:** Without automated e2e tests in CI, we can't prevent regressions and can't safely merge PRs.

## Dependencies

**Blocks:**
- #458 (file upload e2e tests) - need CI to run them automatically
- #459 (crawler e2e tests) - need CI to run them automatically

### Architecture Overview

```
GitHub Actions Runner
├── Services (via GitHub Actions services:)
│   ├── PostgreSQL (main DB) - port 5432
│   ├── PostgreSQL (Keycloak DB) - port 5433
│   └── Typesense - port 8108
│
├── Keycloak Container (via docker run)
│   └── Depends on: gai-keycloak-db service
│
├── Backend Container (via docker run)
│   └── Depends on: PostgreSQL, Typesense, Keycloak
│
├── Frontend Container (via docker run)
│   └── Depends on: Backend API
│
└── E2E Tests (Playwright)
    └── Runs against: http://localhost:3001
```

### Workflow File: `.github/workflows/e2e-tests.yml`

Create new workflow file with the following structure:

```yaml
name: E2E Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  # Database
  DATABASE_URL: postgresql://chatweb:password@localhost:5432/chatweb?schema=public

  # Typesense
  TYPESENSE_API_HOST: localhost
  TYPESENSE_API_PORT: 8108
  TYPESENSE_API_PROTOCOL: http
  TYPESENSE_API_KEY: xyz-test-key

  # Keycloak
  KEYCLOAK_URL: http://localhost:8180
  KEYCLOAK_REALM: george-ai
  KEYCLOAK_CLIENT_ID: george-ai-web
  KEYCLOAK_REDIRECT_URL: http://localhost:3001

  # Backend
  BACKEND_URL: http://localhost:3003
  BACKEND_PUBLIC_URL: http://localhost:3003
  GRAPHQL_API_KEY: TestKey

  # Frontend
  PUBLIC_APP_URL: http://localhost:3001

  # Git
  GIT_COMMIT_SHA: ${{ github.sha }}

  # Ollama (optional - use remote instance or mock)
  OLLAMA_BASE_URL: ${{ secrets.OLLAMA_BASE_URL || 'http://localhost:11434' }}

  # Workers (disabled for e2e tests)
  AUTOSTART_ENRICHMENT_WORKER: false
  AUTOSTART_CONTENT_PROCESSING_WORKER: false

jobs:
  e2e:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    services:
      # Main PostgreSQL database
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: chatweb
          POSTGRES_USER: chatweb
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      # Keycloak PostgreSQL database
      keycloak-db:
        image: postgres:16
        env:
          POSTGRES_DB: keycloak
          POSTGRES_USER: keycloak
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

      # Typesense vector search
      typesense:
        image: typesense/typesense:27.1
        env:
          TYPESENSE_API_KEY: xyz-test-key
        options: >-
          --health-cmd "curl -f http://localhost:8108/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 8108:8108

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.4
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run database migrations
        run: pnpm --filter @george-ai/pothos-graphql prisma:migrate

      - name: Generate Prisma Client
        run: pnpm --filter @george-ai/pothos-graphql prisma:generate

      # Start Keycloak
      - name: Start Keycloak
        run: |
          docker run -d \
            --name keycloak \
            --network host \
            -e KC_DB=postgres \
            -e KC_DB_URL=jdbc:postgresql://localhost:5433/keycloak \
            -e KC_DB_USERNAME=keycloak \
            -e KC_DB_PASSWORD=password \
            -e KC_HOSTNAME=localhost \
            -e KC_HOSTNAME_STRICT=false \
            -e KC_HOSTNAME_STRICT_HTTPS=false \
            -e KC_HTTP_ENABLED=true \
            -e KC_PROXY=edge \
            -e KC_LOG_LEVEL=info \
            -e KC_HEALTH_ENABLED=true \
            -e KEYCLOAK_ADMIN=admin \
            -e KEYCLOAK_ADMIN_PASSWORD=admin \
            quay.io/keycloak/keycloak:26.4 start-dev

      - name: Wait for Keycloak to be ready
        run: |
          echo "Waiting for Keycloak health endpoint..."
          timeout 120 bash -c 'until curl -f http://localhost:8180/health/ready; do sleep 2; done'
          echo "Keycloak is ready!"

      # TODO: Setup Keycloak realm, client, and test user
      # This step needs a script to configure Keycloak via API
      # For now, tests may need to skip auth or use mock

      # Build and start backend
      - name: Build backend Docker image
        run: |
          docker build \
            -f apps/georgeai-backend/Dockerfile \
            -t george-ai-backend:test \
            --build-arg GIT_COMMIT_SHA=${{ github.sha }} \
            .

      - name: Start backend
        run: |
          docker run -d \
            --name backend \
            --network host \
            -e DATABASE_URL="${{ env.DATABASE_URL }}" \
            -e TYPESENSE_API_HOST=localhost \
            -e TYPESENSE_API_PORT=8108 \
            -e TYPESENSE_API_PROTOCOL=http \
            -e TYPESENSE_API_KEY=xyz-test-key \
            -e KEYCLOAK_URL=http://localhost:8180 \
            -e KEYCLOAK_REALM=george-ai \
            -e KEYCLOAK_CLIENT_ID=george-ai-web \
            -e GRAPHQL_API_KEY=TestKey \
            -e BACKEND_URL=http://localhost:3003 \
            -e BACKEND_PUBLIC_URL=http://localhost:3003 \
            -e AUTOSTART_ENRICHMENT_WORKER=false \
            -e AUTOSTART_CONTENT_PROCESSING_WORKER=false \
            -e OLLAMA_BASE_URL=${{ secrets.OLLAMA_BASE_URL || 'http://localhost:11434' }} \
            george-ai-backend:test

      - name: Wait for backend to be ready
        run: |
          echo "Waiting for backend health endpoint..."
          timeout 120 bash -c 'until curl -f http://localhost:3003/health || curl -f http://localhost:3003/graphql; do sleep 2; done'
          echo "Backend is ready!"

      # Build and start frontend
      - name: Build frontend Docker image
        run: |
          docker build \
            -f apps/georgeai-webapp/Dockerfile \
            -t george-ai-webapp:test \
            --build-arg GIT_COMMIT_SHA=${{ github.sha }} \
            --build-arg BACKEND_URL=http://localhost:3003 \
            --build-arg BACKEND_PUBLIC_URL=http://localhost:3003 \
            --build-arg KEYCLOAK_URL=http://localhost:8180 \
            --build-arg KEYCLOAK_REALM=george-ai \
            --build-arg KEYCLOAK_CLIENT_ID=george-ai-web \
            --build-arg KEYCLOAK_REDIRECT_URL=http://localhost:3001 \
            --build-arg PUBLIC_APP_URL=http://localhost:3001 \
            .

      - name: Start frontend
        run: |
          docker run -d \
            --name frontend \
            --network host \
            george-ai-webapp:test

      - name: Wait for frontend to be ready
        run: |
          echo "Waiting for frontend to be ready..."
          timeout 120 bash -c 'until curl -f http://localhost:3001; do sleep 2; done'
          echo "Frontend is ready!"

      # Install Playwright browsers
      - name: Install Playwright browsers
        run: pnpm --filter @george-ai/e2e-tests exec playwright install --with-deps chromium

      # Run E2E tests
      - name: Run E2E tests
        run: pnpm --filter @george-ai/e2e-tests test
        env:
          E2E_USERNAME: ${{ secrets.E2E_USERNAME || 'testuser@example.com' }}
          E2E_PASSWORD: ${{ secrets.E2E_PASSWORD || 'testpassword' }}
          CI: true

      # Upload test results on failure
      - name: Upload Playwright report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e-tests/playwright-report/
          retention-days: 7

      - name: Upload test screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-screenshots
          path: e2e-tests/test-results/
          retention-days: 7

      # Debug: Show container logs on failure
      - name: Show backend logs
        if: failure()
        run: docker logs backend

      - name: Show frontend logs
        if: failure()
        run: docker logs frontend

      - name: Show Keycloak logs
        if: failure()
        run: docker logs keycloak
```

### Phase 1: Basic Workflow Setup
- [ ] Create `.github/workflows/e2e-tests.yml` with basic structure
- [ ] Configure GitHub Actions services (PostgreSQL x2, Typesense)
- [ ] Add database migration step
- [ ] Test that services start successfully

### Phase 2: Keycloak Setup
- [ ] Add Keycloak container with proper configuration
- [ ] Create Keycloak realm setup script (via Admin API or CLI)
- [ ] Create test user for e2e tests
- [ ] Configure Keycloak client settings
- [ ] Add Keycloak health check with proper wait

### Phase 3: Application Containers
- [ ] Build backend Docker image in CI
- [ ] Start backend with correct environment variables
- [ ] Add backend health check with retry logic
- [ ] Build frontend Docker image in CI
- [ ] Start frontend container
- [ ] Add frontend readiness check

### Phase 4: Playwright Integration
- [ ] Install Playwright browsers (chromium only for speed)
- [ ] Configure Playwright for CI environment
- [ ] Run existing login test
- [ ] Verify test passes in CI

### Phase 5: Error Handling & Debugging
- [ ] Add timeout for entire job (30 minutes)
- [ ] Upload Playwright HTML report on failure
- [ ] Upload screenshots/videos on failure
- [ ] Add container logs dump on failure
- [ ] Test failure scenarios to verify artifacts upload

### Phase 6: Optimization (Optional)
- [ ] Cache Docker layers for faster builds
- [ ] Cache pnpm dependencies
- [ ] Run only on relevant file changes (path filters)
- [ ] Add test retry logic (Playwright already configured)
- [ ] Optimize Playwright to run only chromium (not firefox/webkit)

### Option A: Docker Compose (Simpler)
Instead of individual `docker run` commands, use docker-compose:

```yaml
- name: Start all services with Docker Compose
  run: |
    docker compose -f .devcontainer/docker-compose.yml up -d \
      gai-keycloak-db gai-keycloak gai-chatweb-db gai-typesense
```

**Pros:** Simpler, matches local dev environment exactly
**Cons:** May need to modify docker-compose.yml for CI-specific config

### Option B: Pre-built Docker Images
Use published Docker images instead of building in CI:

```yaml
- name: Pull backend image
  run: docker pull ghcr.io/progwise/george-ai/backend:latest
```

**Pros:** Faster (no build time), matches production images
**Cons:** Tests code from previous merge, not current PR

**Recommendation:** Start with building from source (Option as shown above), can optimize later with caching.

## Known Issues & Considerations

1. **Keycloak Realm Setup**: Need to automate realm/client/user creation
   - Solution: Use Keycloak Admin CLI or REST API in workflow
   - Alternative: Import realm JSON file

2. **Test User Credentials**: Store in GitHub Secrets
   - `E2E_USERNAME` and `E2E_PASSWORD` secrets
   - Keycloak script creates user with these credentials

3. **Ollama/LLM Dependency**: Tests shouldn't require real LLM
   - Use mock or remote Ollama instance
   - Most e2e tests (login, upload, UI) don't need LLM

4. **Test Isolation**: Each test run should be clean
   - Database migrations create fresh schema
   - Typesense collections are per-tenant (isolated by library)

5. **Crawl4AI**: Probably not needed for basic e2e tests
   - Skip for initial implementation
   - Can add later if crawler tests (#459) need it

6. **GitHub Actions Timeout**: Set realistic timeout (30 min)
   - Includes: build (5-10min) + startup (2-3min) + tests (1-5min)

7. **Network Mode**: Using `--network host` for simplicity
   - All services accessible via localhost
   - Matches Playwright config baseURL: `http://localhost:3001`

### Local Testing (Act)
Before pushing, test workflow locally with [act](https://github.com/nektos/act):

```bash
# Install act
brew install act

# Run e2e workflow locally (requires Docker)
act -j e2e -W .github/workflows/e2e-tests.yml
```

### First PR Testing Strategy
1. Create workflow file in a PR
2. Comment out test execution step initially
3. Verify all services start and are healthy
4. Add test execution once infrastructure is working
5. Debug using uploaded artifacts and container logs

## Success Criteria

- [ ] GitHub Actions workflow runs on every PR and push to main
- [ ] All required services (PostgreSQL, Keycloak, Typesense) start successfully
- [ ] Backend and frontend containers build and start
- [ ] Existing login test passes in CI
- [ ] Test artifacts (reports, screenshots) upload on failure
- [ ] Total workflow runtime < 15 minutes (build + test)
- [ ] Workflow is maintainable and well-documented

## Code References

**Existing Workflows:**
- Unit test job example: `.github/workflows/basic-checks.yml:98-126`
- Docker build example: `.github/workflows/build-publish-dockers.yml`

**Configuration Files:**
- Playwright config: `e2e-tests/playwright.config.ts`
- Docker services: `.devcontainer/docker-compose.yml`
- Backend Dockerfile: `apps/georgeai-backend/Dockerfile`
- Frontend Dockerfile: `apps/georgeai-webapp/Dockerfile`

**Environment Variables:**
- Root example: `.env.example`
- E2E example: `e2e-tests/.env.example`

## Related Issues

- #328 - ✅ CLOSED - Playwright End2End Login Tests locally (DEPENDENCY RESOLVED)
- #458 - File upload/embed e2e tests (BLOCKED BY THIS ISSUE)
- #459 - Crawler e2e tests (BLOCKED BY THIS ISSUE)

---

**Note:** This specification is comprehensive and production-ready. The workflow can be implemented incrementally using the phases outlined above. Start with Phase 1-2 to get basic infrastructure working, then add application containers and tests.
